updates tests and conf files can now contains multiline defaults

diff --git a/tasks/backup-pi b/tasks/backup-pi
--- a/tasks/backup-pi
+++ b/tasks/backup-pi
@@ -5,9 +5,9 @@
 images_path=/mnt/storage/images/
 
 if [[ -n "${2}" ]]; then
-  if [[ ! -f "${2}" ]]; then
-    echo "Could not find file \'${1}\'; exiting..."
-    exit
+  if [[ ! -f "${1}" ]]; then
+    printf "Could not find file 's%'; exiting..." "${1}" >&2
+    exit 1
   fi
 
   image_filename="${2}"
@@ -15,20 +15,20 @@ if [[ -n "${2}" ]]; then
   if [[ -n "${1}" ]]; then
 
     # final check that we have an device path
-    if [[ $(lsblk -dnpo name | grep "^${1}$") ]]; then
+    if lsblk -dpo name | grep -q "^${1}$"; then
       disk="${1}"
       sudo dd if="${disk}" iflag=fullblock bs=8M status=progress | gzip > "${image_filename}"
       echo "completed" >> "${0%.*}".log
-      exit
+      exit 0
     else
       echo "invalid device path:${2}; exiting..."
-      exit
+      exit 0
     fi
   fi
 
 else
 
- read -p "Enter image file name to backup:" image_filename
+ read -p -r "Enter image file name to backup:" image_filename
 
 fi
 
@@ -40,13 +40,13 @@ fi
 # -e 11 (exclude CDROM drives")
 
 echo
-if [[ -z $(lsblk -e 11 -o rm | grep " 1") ]]; then
+if lsblk -e 11 -o rm | grep -q " 1"; then
    echo "no removable disks found; exiting..."
    exit
 fi
 
 echo "=Disks==========================================================="
-echo "$(lsblk -e 11 -o name,size,type,tran,model,rm)" #| grep " 1$" | sed 's![^ ]*$!!')
+lsblk -e 11 -o name,size,type,tran,model,rm #| grep " 1$" | sed 's![^ ]*$!!')
 echo "================================================================="
 
   # create an array with all the filer/dir inside ~/myDir
@@ -65,7 +65,7 @@ echo "================================================================="
     fi
 
     # now we can use the selected file
-    echo "\'${disk}\' selected"
+    printf "'%s' selected" "${disk}"
 
     # it'll ask for another unless we leave the loop
     break
@@ -73,16 +73,15 @@ echo "================================================================="
 
 echo
 echo "backing up disk ${disk} to image ${images_path}${image_filename}"
-read -p "Do you want to proceed? (y/n) " confirm
-
-case "${confirm}" in
-	y ) echo;;
-	n ) echo exiting...;
-          exit;;
-	* ) echo invalid response;
-          continue;;
-esac
-
+while read -p -r "Do you want to proceed? (y/n) " confirm; do
+  case "${confirm}" in
+    y ) echo; break;;
+    n ) echo exiting...;
+            exit 0;;
+    * ) echo invalid response;
+            continue;;
+  esac
+done
 # dummy sudo ls (ls could be any call) to elevate
 # permissions before the nohup call
 sudo ls 1>/dev/null 2>/dev/null
@@ -92,7 +91,8 @@ sudo ls 1>/dev/null 2>/dev/null
 # we call this script again with the args we have set
 # this is so that nohup names the process with the name of this script
 # so its easy to find and kill if required.
-echo 'use `echo $(<./restore-pi.log)` to get progress updates'
+# shellcheck disable=SC2016
+echo 'use echo $(<./restore-pi.log) to get progress updates'
 
 nohup "${0}" "${disk}" "${images_path}${image_filename}" > "${0%.*}".log &
 
diff --git a/tasks/make-packages b/tasks/make-packages
--- a/tasks/make-packages
+++ b/tasks/make-packages
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
  
 this_path="$(dirname "${BASH_SOURCE[0]}")"
 
@@ -12,36 +12,49 @@ elif [[ "${1}" == "-c" ]]; then
 fi
 
 declare -a build_items=()
- 
-pushd "${this_path}/../feed" || exit 1
- 
-if [[ "$build" == "all" ]]; then
-  build_items=("network-gps" "dbus-ne-shunt" "test-service" 
-  "test-install" "dbus-relay-board" "mount-shares" "opkg-helpers")
-elif [[ "$build" == "package" ]]; then
-  build_items=("package")
-else
-  build_items=("${@}")
-fi
+declare -a folders=("../services" "../utils")
+declare pwd_old=$PWD
+
+cd "${this_path}/../feed" || exit 1
 
 build_feed_package() {
-  pushd "${this_path}/../feed" || exit 1
   opkg-make-index ./ -p Packages
-  popd || exit 1
 }
-
+ 
+if [[ "$build" == "all" ]]; then
+  mapfile -t build_items < <(find "${folders[@]}" -mindepth 1 -maxdepth 1 -type d)
+elif [[ "$build" == "package" ]]; then
+  build_feed_package
+else
+  build_items=("${@}")
+  #build_items=("opkg-helpers" "test-service")
+  declare -i found=0 i 
+  declare f
+ 
+  for i in "${!build_items[@]}"; do
+    for f in "${folders[@]}"; do
+      if [[ -d "${f}/${build_items[$i]}" ]]; then
+        build_items[i]="$f/${build_items[$i]}"
+        found=1
+        break;
+      fi
+    done
+    (( found==0)) && { echo "invalid package:${build_items[$i]}" >&2; return 1; }
+    found=0
+  done
+ 
+fi
+ 
 build_package() {
-  name="${1}"
+
+  path="${1}/src"
+  name="$(basename "${1}")"
   echo "building ${name}"
 
-  path_name="services"
-  case ${1} in
-    "mount-shares") path_name="utils";;
-    "opkg-helpers") path_name="utils";;
-  esac
+  [[ -d "${path}" ]] || { echo "invalid path:${path}" >&2 ; return 1; }
 
-  opkg-build -o root -g root "../${path_name}/${name}/src" ./
-  popd || exit 1
+  opkg-build -o root -g root "${path}" ./
+
 }
  
 for pkg in "${build_items[@]}"; do
@@ -55,3 +68,5 @@ if [[ -n "$comment" ]]; then
   git commit -am "${comment}"
   git push
 fi
+
+cd "$pwd_old" || true
diff --git a/tasks/restore-pi b/tasks/restore-pi
--- a/tasks/restore-pi
+++ b/tasks/restore-pi
@@ -6,8 +6,8 @@ images_path=/mnt/storage/images
 
 if [[ -n "${1}" ]]; then
   if [[ ! -f "${1}" ]]; then
-    echo "Could not find file \'${1}\'; exiting..."
-    exit
+    printf "Could not find file 's%'; exiting..." "${1}" >&2
+    exit 1
   fi
 
   image_filename="${1}"
@@ -15,17 +15,17 @@ if [[ -n "${1}" ]]; then
   if [[ -n "${2}" ]]; then
 
     # final check that we have an device path
-    if [[ $(lsblk -dnpo name | grep "^${2}$") ]]; then
+    if lsblk -dpo name | grep -q "^${2}$"; then
       disk="${2}"
 
       gunzip -c "${image_filename}" | \
            sudo dd of="${disk}" iflag=fullblock bs=2M status=progress
 
       echo "completed" >> "${0%.*}".log
-      exit
+      exit 0
     else
       echo "invalid device path:${2}; exiting..."
-      exit
+      exit 0
     fi
   fi
 
@@ -56,8 +56,7 @@ if [[ -z "${image_filename}" ]]; then
   echo "no image file found; exiting..."
   exit
 fi
-
-
+ 
 # -e 11 (exclude CDROM drives")
 
 echo
@@ -67,7 +66,7 @@ if [[ -z $(lsblk -e 11 -o rm | grep " 1") ]]; then
 fi
 
 echo "=Disks==========================================================="
-echo "$(lsblk -e 11 -o name,size,type,tran,model,rm)" #| grep " 1$" | sed 's![^ ]*$!!')
+lsblk -e 11 -o name,size,type,tran,model,rm #| grep " 1$" | sed 's![^ ]*$!!')
 echo "================================================================="
 
   # create an array with all the filer/dir inside ~/myDir
@@ -86,7 +85,7 @@ echo "================================================================="
     fi
 
     # now we can use the selected file
-    echo "\'${disk}\' selected"
+    printf "'%s' selected" "${disk}"
 
     # it'll ask for another unless we leave the loop
     break
@@ -94,23 +93,22 @@ echo "================================================================="
 
 echo
 echo "Restoring image ${image_filename} to disk ${disk}"
-read -p "Do you want to proceed? (y/n) " confirm
-
-case "${confirm}" in
-	y ) echo;;
-	n ) echo exiting...;
-          exit;;
-	* ) echo invalid response;
-          continue;;
-esac
-
+while read -p -r "Do you want to proceed? (y/n) " confirm; do
+  case "${confirm}" in
+    y ) echo; break;;
+    n ) echo exiting...;
+            exit 0;;
+    * ) echo invalid response;
+            continue;;
+  esac
+done
 # dummy sudo ls (ls could be any call) to elevate
 # permissions before the nohup call
 sudo ls 1>/dev/null 2>/dev/null
 touch "${0%.*}".log
 
 # here we use nohup so that the process works in the background and
-# can logout of ssh terminals.
+# we can logout of ssh terminals.
 # we call this script again with the args we have set
 # this is so that nohup names the process with the name of this script
 # so its easy to find and kill if required.
diff --git a/utils/opkg-helpers/src/data/opkg-helpers/libs/core-lib b/utils/opkg-helpers/src/data/opkg-helpers/libs/core-lib
--- a/utils/opkg-helpers/src/data/opkg-helpers/libs/core-lib
+++ b/utils/opkg-helpers/src/data/opkg-helpers/libs/core-lib
@@ -9,6 +9,18 @@
 #   source core-utils-lib.sh
 #######################################
 
+# ___assert_depends() {
+#   if [[ -v "__this_path" ]]; then
+#     echo "__this_path variable missing" >&2; exit 0; fi
+  
+#   local name="$1"
+ 
+#   if [[ -f "$__this_path/$name" ]]; then
+#     echo "depenency missing $__this_path/$name" >&2; exit 0; fi
+# }
+
+
+
 ######################################
 # expands the path to a full path
 # does not follow symlinks, even for
@@ -143,5 +155,5 @@ EOF
   ' "$script"
 }
 
-[[ "$1" = "core_utils_lib_list_methods_in_script" ]] && { shift; core_lib_list_methods_in_script "$@"; }
+[[ "${1:-}" = "core_utils_lib_list_methods_in_script" ]] && { shift; core_lib_list_methods_in_script "$@"; }
 
