Update package metadata and enhance dbus settings handling in opkg-manager and related scripts

diff --git a/utils/opkg-manager/src/data/opkg-manager/dbus-common b/utils/opkg-manager/src/data/opkg-manager/dbus-common
--- a/utils/opkg-manager/src/data/opkg-manager/dbus-common
+++ b/utils/opkg-manager/src/data/opkg-manager/dbus-common
@@ -58,7 +58,21 @@ dbus_common_remove_settings() {
 	}
 		
 }
- 
+
+dbus_common_set_string_value() {
+	local path="${1}"
+	local value="${2}"
+	
+	if ! dbus -y com.victronenergy.settings "${path}" SetValue "${value}" &>/dev/null; then
+		echo "adding new setting"
+		if dbus -y com.victronenergy.settings / AddSettings "%[ {'path':'${path}', 'default':''} ]" &>/dev/null; then
+			echo "setting value"
+			dbus -y com.victronenergy.settings "${path}" SetValue "${value}" &> /dev/null &&
+					exit 1
+		fi
+		echo "error adding value" >&2
+	fi
+}
 
 # Function: dbus_common_get_value
 # Get a value from the dbus settings service
