Refactor Themer and OpkgManager integration
- Updated addsymlinks-qml to correctly set plugin source and target paths.
- Enhanced post-install and pre-remove scripts in the Themer package to include common patching functions.
- Introduced new functions in the Themer common script for patching and removing patches from QML files.
- Added new QML files for theming, including Themer, ThemerMbStyle, and ThemerOverviewConnectionEnd.
- Removed obsolete QML files (TmMbStyle, TmOverviewConnectionEnd, TmPageStackWindow).
- Updated addsymlinks-qml test script to reflect new file structure.
- Created configuration and schema files for dbus-inetbox service.
- Implemented PageSettingsInetboxDeviceSetup.qml for device setup UI.
- Adjusted Venus workspace configuration for better organization.

diff --git a/utils/opkg-manager/src/data/opkg-manager/serial-device-installer-qml b/utils/opkg-manager/src/data/opkg-manager/serial-device-installer-qml
--- a/utils/opkg-manager/src/data/opkg-manager/serial-device-installer-qml
+++ b/utils/opkg-manager/src/data/opkg-manager/serial-device-installer-qml
@@ -55,11 +55,26 @@ sdi_detect_usb_device() {
 }
 
 sdi_apply_device() {
-  echo "this"
-  sleep 2
-  echo "that"
-  sleep 1
-  echo "done"
+  
+  local this_path=$(dirname "${BASH_SOURCE[0]}")
+  . $this_path/serial-device-installer
+  . $this_path/libs/conf-lib
+  INTERACTIVE=0
+
+  local confFile=/data/dev/services/dbus-inetbox/src/data/dbus-inetbox/dbus-inetbox.conf
+  conf_lib_load_with_schema "$confFile"
+ 
+  TTY=ttyACM0 # todo get tty from json
+ 
+  UDEVADM_PROPS="ID_VENDOR=FTDI|ID_MODEL=Intetbox|ID_SERIAL=FTDI_Intetbox_BG02CS2X"
+ 
+  serial_device_installer_install
+  local -i retval=$?
+  if ((retval == 0)); then
+    echo "succeeded"
+  else
+    echo "failed"
+  fi
 }
 
 sdi_get_process_from_usb_port() {
@@ -237,12 +252,13 @@ case "${1:-}" in
 		;;
   apply-device)
     shift
-    sdi_apply_device "${1}"
+    sdi_apply_device "${1:-}"
     ;;
   *)
     if [[ -n ${1:-} ]]; then
-      echo "serial-device-installer-qml: incorrect command : ${1}" >&2
+      echo "serial-device-installer-qml: invalid command : ${1}" >&2
     fi
     ;;
 esac
- 
+
+# sdi_apply_device
