Mostly finished gui-v2. Moved the opkg-manager over to a dbus solution

diff --git a/addons/opkg-manager/src/data/opkg-manager/install-helper b/addons/opkg-manager/src/data/opkg-manager/install-helper
--- a/addons/opkg-manager/src/data/opkg-manager/install-helper
+++ b/addons/opkg-manager/src/data/opkg-manager/install-helper
@@ -10,9 +10,9 @@ PACKAGE_ACTION="${1:-}"
 # set package name using the path of the calling file's location
 PACKAGE_NAME="${PACKAGE_NAME-"$(basename "$(dirname "$(realpath "${0}")")")"}"
 PACKAGE_DBUS_SETTINGS="${PACKAGE_DBUS_SETTINGS-}"
-PACKAGE_CUSTOM_SERVICE_KEY="${PACKAGE_CUSTOM_SERVICE_KEY-}"
-PACKAGE_CUSTOM_SERVICE_NAME="${PACKAGE_CUSTOM_SERVICE_NAME-}"
-PACKAGE_CUSTOM_SERVICE_DISPLAY_NAME="${PACKAGE_CUSTOM_SERVICE_DISPLAY_NAME-}"
+PACKAGE_CUSTOM_DEVICE_KEY="${PACKAGE_CUSTOM_DEVICE_KEY-}"
+PACKAGE_CUSTOM_DEVICE_SERVICE_NAME="${PACKAGE_CUSTOM_DEVICE_SERVICE_NAME-}"
+PACKAGE_CUSTOM_DEVICE_DISPLAY_NAME="${PACKAGE_CUSTOM_DEVICE_DISPLAY_NAME-}"
 
 PACKAGE_VERSION_NEW=
 PACKAGE_VERSION_CURRENT=
@@ -23,42 +23,23 @@ PACKAGE_VERSION_CURRENT=
 [[ ${DEV_INSTALL:-} == 1 ]] && [[ -d /data/dev/addons/opkg-manager/src ]] &&
 	export VE_ROOT_PATH=/data/dev/addons/opkg-manager/src
 
-# shellcheck source=/data/dev/addons/opkg-manager/src/data/opkg-manager/source-common
-[[ -n "${__SOURCE_COMMON_SOURCED:-}" ]] || { 
+
+[[ -n "${__SOURCE_COMMON_SOURCED:-}" ]] || {
+	# shellcheck source=/data/dev/addons/opkg-manager/src/data/opkg-manager/source-common
 	source "${VE_ROOT_PATH:-}/data/opkg-manager/source-common" && __SOURCE_COMMON_SOURCED=1; }
 
 __try_call() {
 	local calling_method="${1}"
-  
-	if declare -F ${calling_method} >/dev/null; then
+	if declare -F "${calling_method}" >/dev/null; then
 		shift
-		${calling_method} "$@" 
+		${calling_method} "$@"
 	fi
 }
 
-install_helper_add_remove_dbus_csv_items() {
-	
-	local csv_string=
-	local command="$1"
-  local dbusPath="$2"
-	shift 2
-
-	dbus_common_get_value "${dbusPath}" csv_string
-
-	__install_helper_add_remove_comma_delimited_string "$command" csv_string "$@" 
-
-	if [[ -z "${csv_string}" ]]; then
-		dbus_common_remove_settings <<< "{'path':'${dbusPath}'}"
-		return 0
-	fi
-
-	dbus_common_set_string_value "${dbusPath}" "${csv_string}"
-}
-
-__install_helper_has_custom_service_vars() {
-	[[ -n "${PACKAGE_CUSTOM_SERVICE_KEY:-}" ]] ||
-	[[ -n "${PACKAGE_CUSTOM_SERVICE_NAME:-}" ]] ||
-	[[ -n "${PACKAGE_CUSTOM_SERVICE_DISPLAY_NAME:-}" ]]
+__install_helper_has_custom_device_vars() {
+	[[ -n "${PACKAGE_CUSTOM_DEVICE_KEY:-}" ]] ||
+	[[ -n "${PACKAGE_CUSTOM_DEVICE_SERVICE_NAME:-}" ]] ||
+	[[ -n "${PACKAGE_CUSTOM_DEVICE_DISPLAY_NAME:-}" ]]
 }
 
 __install_helper_has_custom_overview_pages() {
@@ -197,95 +178,44 @@ EOF
 	done
 }
 
-__install_helper_require_custom_service_vars() {
-	__install_helper_has_custom_service_vars || return 1
+__install_helper_require_custom_device_vars() {
+	__install_helper_has_custom_device_vars || return 1
 
-	[[ -n "${PACKAGE_CUSTOM_SERVICE_KEY:-}" ]] || {
-		echo "ERROR: PACKAGE_CUSTOM_SERVICE_KEY not set" >&2
+	[[ -n "${PACKAGE_CUSTOM_DEVICE_KEY:-}" ]] || {
+		echo "ERROR: PACKAGE_CUSTOM_DEVICE_KEY not set" >&2
 		return 1
 	}
-	[[ -n "${PACKAGE_CUSTOM_SERVICE_NAME:-}" ]] || {
-		echo "ERROR: PACKAGE_CUSTOM_SERVICE_NAME not set" >&2
+	[[ -n "${PACKAGE_CUSTOM_DEVICE_SERVICE_NAME:-}" ]] || {
+		echo "ERROR: PACKAGE_CUSTOM_DEVICE_SERVICE_NAME not set" >&2
 		return 1
 	}
-	[[ -n "${PACKAGE_CUSTOM_SERVICE_DISPLAY_NAME:-}" ]] || {
-		echo "ERROR: PACKAGE_CUSTOM_SERVICE_DISPLAY_NAME not set" >&2
+	[[ -n "${PACKAGE_CUSTOM_DEVICE_DISPLAY_NAME:-}" ]] || {
+		echo "ERROR: PACKAGE_CUSTOM_DEVICE_DISPLAY_NAME not set" >&2
 		return 1
 	}
 
 	return 0
 }
 
-install_helper_add_custom_service() {
-	__install_helper_require_custom_service_vars || return 1
+install_helper_add_custom_device() {
+	__install_helper_require_custom_device_vars || return 1
 
 	dbus_common_add_settings <<EOF
-{'path':'/Settings/OpkgManager/CustomServices/${PACKAGE_CUSTOM_SERVICE_KEY}/ProductName', 'default':'${PACKAGE_CUSTOM_SERVICE_DISPLAY_NAME}'}
-{'path':'/Settings/OpkgManager/CustomServices/${PACKAGE_CUSTOM_SERVICE_KEY}/ServiceName', 'default':'${PACKAGE_CUSTOM_SERVICE_NAME}'}
+{'path':'/Settings/OpkgManager/CustomDevices/${PACKAGE_CUSTOM_DEVICE_KEY}/ProductName', 'default':'${PACKAGE_CUSTOM_DEVICE_DISPLAY_NAME}'}
+{'path':'/Settings/OpkgManager/CustomDevices/${PACKAGE_CUSTOM_DEVICE_KEY}/ServiceName', 'default':'${PACKAGE_CUSTOM_DEVICE_SERVICE_NAME}'}
 EOF
-
-	install_helper_add_remove_dbus_csv_items "add" "/Settings/OpkgManager/AvailableCustomServices" "${PACKAGE_CUSTOM_SERVICE_KEY}"
+	dbus_common_add_dbus_csv_values "/Settings/OpkgManager/CustomDevicesList" "${PACKAGE_CUSTOM_DEVICE_KEY}"
 }
 
-install_helper_remove_custom_service() {
-	__install_helper_require_custom_service_vars || return 1
+install_helper_remove_custom_device() {
+	__install_helper_require_custom_device_vars || return 1
 
 	dbus_common_remove_settings <<EOF
-{'path':'/Settings/OpkgManager/CustomServices/${PACKAGE_CUSTOM_SERVICE_KEY}/ProductName'}
-{'path':'/Settings/OpkgManager/CustomServices/${PACKAGE_CUSTOM_SERVICE_KEY}/ServiceName'}
+{'path':'/Settings/OpkgManager/CustomDevices/${PACKAGE_CUSTOM_DEVICE_KEY}/ProductName'}
+{'path':'/Settings/OpkgManager/CustomDevices/${PACKAGE_CUSTOM_DEVICE_KEY}/ServiceName'}
 EOF
 
-	install_helper_add_remove_dbus_csv_items "remove" "/Settings/OpkgManager/AvailableCustomServices" "${PACKAGE_CUSTOM_SERVICE_KEY}"
-}
-
-# function: __install_helper_add_remove_comma_delimited_string
-# adds or removes any item from a command delimited string
-# arg1: 
-#				The command, "add|remove"
-# arg2: (byref)
-#				The comma delimited string
-# arg3: 
-#				The items to add|remove from the string
-__install_helper_add_remove_comma_delimited_string() {
-	local command="${1}"
-	local -n _csv_string="${2}"
-	shift 2
-	local item
-	local -a cur_items=()
-	local -a result=()
-
-	IFS=',' read -ra cur_items <<< "${_csv_string}"
-
-	if [[ "${command}" == "add" ]]; then
-		local -A _seen=()
-		for item in "${cur_items[@]}"; do
-			[[ -z "${item}" ]] && continue
-			[[ -v _seen["${item}"] ]] && continue
-			_seen["${item}"]=1
-			result+=("${item}")
-		done
-		for item in "$@"; do
-			[[ -v _seen["${item}"] ]] && continue
-			_seen["${item}"]=1
-			result+=("${item}")
-		done
-	elif [[ "${command}" == "remove" ]]; then
-		local -A _remove=()
-		for item in "$@"; do
-			_remove["${item}"]=1
-		done
-		local -A _seen=()
-		for item in "${cur_items[@]}"; do
-			[[ -z "${item}" ]] && continue
-			[[ -v _remove["${item}"] ]] && continue
-			[[ -v _seen["${item}"] ]] && continue
-			_seen["${item}"]=1
-			result+=("${item}")
-		done
-	fi
-
-	local IFS=','
-	_csv_string="${result[*]-}"
+	dbus_common_remove_dbus_csv_values "/Settings/OpkgManager/CustomDevicesList" "${PACKAGE_CUSTOM_DEVICE_KEY}"
 }
 
 # arguments {1} (optional): set to remove to remove
@@ -299,9 +229,9 @@ install_helper_add_remove_patch() {
   else
 		msg="Patching files"
 	fi
- 
+
 	shopt -s nullglob
-  
+
   local installer_path; installer_path="$(dirname "$(realpath "${0}")")"
 
 	for patchfile in "$installer_path"/*.patch; do
@@ -337,11 +267,11 @@ install_helper_restart_gui_service() {
 }
 
 install_helper_install() {
- 
+
   [[ -z "${PACKAGE_NAME:-}" ]] && { echo "ERROR: PACKAGE_NAME not set"; return 1; }
 	__install_helper_validate_custom_overview_pages_definition || return 1
 	__install_helper_validate_custom_menus_definition || return 1
-	
+
 	install_helper_initialize
 
 	__try_call "pre_install"
@@ -354,13 +284,13 @@ install_helper_install() {
 	fi
 
 	install_helper_add_remove_patch add
- 
+
   [[ -n "${PACKAGE_DBUS_SETTINGS:-}" || -n "${PACKAGE_DBUS_SETTINGS_DEPRECATED:-}" ]] &&
 		echo "Adding dbus settings"
-		
+
 	[[ -n "${PACKAGE_DBUS_SETTINGS_DEPRECATED:-}" ]] &&
 		dbus_common_remove_settings <<< "${PACKAGE_DBUS_SETTINGS_DEPRECATED}"
- 
+
 	[[ -n "${PACKAGE_DBUS_SETTINGS:-}" ]] && {
 		dbus_common_add_settings <<< "${PACKAGE_DBUS_SETTINGS}"
 	}
@@ -373,13 +303,13 @@ install_helper_install() {
 		install_helper_add_custom_menus || return 1
 	fi
 
-	if __install_helper_has_custom_service_vars; then
-		install_helper_add_custom_service || return 1
+	if __install_helper_has_custom_device_vars; then
+		install_helper_add_custom_device || return 1
 	fi
 
-	if [[ -n "${PACKAGE_CUSTOM_SERVICE_NAME}" ]]; then 
+	if [[ -n "${PACKAGE_CUSTOM_DEVICE_SERVICE_NAME}" ]]; then
 		addsource "serial-device-installer"
-		DEVICE_SERVICE_NAME="${PACKAGE_CUSTOM_SERVICE_NAME}"
+		DEVICE_SERVICE_NAME="${PACKAGE_CUSTOM_DEVICE_SERVICE_NAME}"
 		serial_device_installer_add_service_mapping
 		install_helper_update_services
 	fi
@@ -387,7 +317,7 @@ install_helper_install() {
 	__try_call "post_install"
 
 	install_helper_restart_gui_service
- 
+
 	echo "Finished $PACKAGE_ACTION"
 
 	return 0
@@ -395,12 +325,12 @@ install_helper_install() {
 
 install_helper_uninstall_services() {
 	addsource "serial-device-installer"
-	DEVICE_SERVICE_NAME="${PACKAGE_CUSTOM_SERVICE_NAME}"
- 
+	DEVICE_SERVICE_NAME="${PACKAGE_CUSTOM_DEVICE_SERVICE_NAME}"
+
   local args=
 	[[ "$PACKAGE_ACTION" == "upgrade-remove" ]] &&
 		args="--no-remove-usb-rule --no-remove-service-mapping"
-	
+
 	serial_device_installer_uninstall_package $args # do not use "
 }
 
@@ -411,13 +341,13 @@ install_helper_update_services() {
 	echo "Restarting services..."
 
 	addsource "serial-device-installer"
-	DEVICE_SERVICE_NAME="${PACKAGE_CUSTOM_SERVICE_NAME}"
+	DEVICE_SERVICE_NAME="${PACKAGE_CUSTOM_DEVICE_SERVICE_NAME}"
 	serial_device_installer_restart_services
 }
 
 
 install_helper_remove() {
- 
+
 	[[ -z "$PACKAGE_NAME" ]] && { echo "ERROR: PACKAGE_NAME not set"; return 1; }
 	__install_helper_validate_custom_overview_pages_definition || return 1
 	__install_helper_validate_custom_menus_definition || return 1
@@ -433,9 +363,9 @@ install_helper_remove() {
 
 	install_helper_add_remove_patch remove
 
-	if __install_helper_has_custom_service_vars; then
+	if __install_helper_has_custom_device_vars; then
 		echo "Removing custom service settings"
-		install_helper_remove_custom_service || return 1
+		install_helper_remove_custom_device || return 1
 	fi
 
 	[[ -n "${PACKAGE_DBUS_SETTINGS:-}" ]] && {
@@ -453,15 +383,15 @@ install_helper_remove() {
 		install_helper_remove_custom_menus || return 1
 	fi
 
-	if [[ -n "${PACKAGE_CUSTOM_SERVICE_NAME}" ]]; then
-		echo "Removing services for ${PACKAGE_CUSTOM_SERVICE_NAME}"
+	if [[ -n "${PACKAGE_CUSTOM_DEVICE_SERVICE_NAME}" ]]; then
+		echo "Removing services for ${PACKAGE_CUSTOM_DEVICE_SERVICE_NAME}"
 		install_helper_uninstall_services
 	fi
- 
+
 	__try_call "post_remove"
 
 	install_helper_restart_gui_service
-	
+
 	if [[ $PACKAGE_ACTION == "upgrade-remove" ]]; then
 		echo "Removed previous install, upgrading now..."
 	else
@@ -475,9 +405,10 @@ install_helper_remove() {
 
 if [[ $PACKAGE_ACTION == "configure" ]]; then
   declare package_no_extension="${2%.*}"
- 
+
 	#PACKAGE_NAME="$(awk '/Package:/ {print $2}' ${package_no_extension}.control)"
-	PACKAGE_VERSION_NEW="$(awk '/Version:/ {print $2}' ${package_no_extension}.control 2>/dev/null)"
+	# shellcheck disable=SC2034  # Unused in other scripts
+	PACKAGE_VERSION_NEW="$(awk '/Version:/ {print $2}' "${package_no_extension}".control 2>/dev/null)"
 	PACKAGE_VERSION_CURRENT="$(opkg status "$PACKAGE_NAME" 2>/dev/null | awk '/Version:/ {print $2}' 2>/dev/null)"
 	[[ -z "$PACKAGE_VERSION_CURRENT" ]] \
 		&& PACKAGE_ACTION="install" \
@@ -487,12 +418,10 @@ elif [[ "$PACKAGE_ACTION" == "upgrade" ]]; then
 	PACKAGE_ACTION="upgrade-remove"
 fi
 echo "Install Action: $PACKAGE_ACTION"
- 
+
 case "${PACKAGE_ACTION}" in
   install|upgrade-install|configure|dev-install)
 		install_helper_install;;
   remove|upgrade|upgrade-remove|dev-remove)
     install_helper_remove;;
 esac
-
-
diff --git a/addons/opkg-manager/src/data/opkg-manager/opkg-bridge/device b/addons/opkg-manager/src/data/opkg-manager/opkg-bridge/device
--- a/addons/opkg-manager/src/data/opkg-manager/opkg-bridge/device
+++ b/addons/opkg-manager/src/data/opkg-manager/opkg-bridge/device
@@ -8,15 +8,16 @@
 set -o nounset
 
 declare _this_path; _this_path=$(dirname "${BASH_SOURCE[0]}")
- 
+
 source "$_this_path/../dbus-common"
 source "$_this_path/../serial-device-installer"
 
 DEFAULT_USB_PROPS="ID_MODEL,ID_VENDOR,ID_SERIAL"
 
+
 # __device_send_props_as_json <associated array of properties>
 # takes an associated array of properties and returns a JSON string of properties.
-__device_send_props_as_json() {
+__device_send_props_to_json_result() {
   local -n assoc_ref="$1"
   local json="{"
   local first=1
@@ -29,40 +30,42 @@ __device_send_props_as_json() {
     escaped_value=${value//\\/\\\\}
     escaped_value=${escaped_value//\"/\\\"}
     (( first )) && first=0 || json+=","
- 
+
     json+="\"${escaped_key}\":\"${escaped_value}\""
   done
 
   json+="}"
-  printf '%s\n' "$json"
+
+  dbus -y "com.victronenergy.opkgmanager" "/Result/Json" SetValue "$json" 1>/dev/null
+
 }
 
 # __autoReconnect <service path> <out tty>
 # for testing... re-connects the usb device without physically re-plugging in the device
-# <service path> The name of the path at OpkgManager/CustomServices/${service_path}/DEVICE_TTY
+# <service path> The name of the path at OpkgManager/CustomDevices/${service_path}/DEVICE_TTY
 # <out tty> The name of the usb port
 __autoReconnect() {
   [[ -z "${1:-}" ]] && return
-  
+
   local service_path="${1}"
   local -n device="${2}"
- 
-  dbus_common_get_value "/Settings/OpkgManager/CustomServices/${service_path}/TestTTY" device
- 
+
+  dbus_common_get_value "/Settings/OpkgManager/CustomDevices/${service_path}/TestTTY" device
+
   [[ -z $device || ! -e /dev/$device ]] && return 0 # no device or device does not exist
-  
+
   echo "Auto connecting device: $device"
   (
     local this_path; this_path=$(dirname "${BASH_SOURCE[0]}")
-    $this_path/../libs/usb-lib "reconnect" "$device" 1>/dev/null 2>/dev/null
+    "$this_path/../libs/usb-lib" "reconnect" "$device" 1>/dev/null 2>/dev/null
     (($?==0)) && echo "✓ Reconnect succeeded" || echo "✗ Reconnect failed"
   )
 }
- 
+
 # device_detect_usb <dbus service path> <autoReconnect (optional)>
 # usage device_detect_usb "Inetbox" "ttyUSB0"
-# <dbus service path> is the name of the Custom Service 
-#  i.e. Inetbox =/OpkgManager/CustomServices/Inetbox/...
+# <dbus service path> is the name of the Custom Service
+#  i.e. Inetbox =/OpkgManager/CustomDevices/Inetbox/...
 # detects the usb device that gets plugged in to a port
 # Returns a json string containing:
 #  port: < the tty port name i.e. ttyUSB0 >
@@ -71,33 +74,35 @@ __autoReconnect() {
 #  usbProps: < a | separated list of usb properties the supplied service path requires >
 device_detect_usb() {
   # Configurable property list (edit as needed)
- 
+
   local service_path="${1}"
   local autoReconnect="${2:-}"
   local tty=
- 
+
   if [[ -n $autoReconnect ]]; then
-    __autoReconnect $service_path tty
+    __autoReconnect "$service_path" tty
   fi
- 
+
   [[ -z $tty ]] && device_get_usb_port tty
   [[ -e "/dev/${tty}" ]] || { echo "Device not found" >&2; return 1; }
- 
+
   echo "✓ Found device: $tty"
 
   local -A json_props
   local usb_props=
-  local process_pid= process_name= possible_process_name=
-  local service_name= 
+  local process_pid=
+	local process_name=
+	local possible_process_name=
+  local service_name=
 
   __fill_usb_props "$tty" "${service_path}" usb_props
-  
+
   #echo "usb_props=$usb_props"
   echo "Getting device status..."
 
   # notes
   # fuser can be used to get the pid from the tty port
-  # svstat can return pid of the service when up. 
+  # svstat can return pid of the service when up.
   # A service may be running, but not using the tty port (might be crashing, etc.)
   #   so need to poll svstat first to see if service name is available, then fuser as a backup
   # Try to get the service name using the VE_SERVICE and the serial-starter.conf file
@@ -119,13 +124,13 @@ device_detect_usb() {
 
   device_get_stable_tty_process_pid "$service_name_or_tty" process_pid possible_process_name
   process_state=$?
- 
+
   if (( process_state == 0 )); then
     if [[ -n "${DEVICE_SERVICE_NAME:-}" ]]; then
       service_name="${DEVICE_SERVICE_NAME:-}"
     elif ! device_find_service_from_pid "$process_pid" "$tty" service_name; then
       process_name=$(ps -p "$process_pid" -o comm= 2>/dev/null | tr -d ' ')
-    fi 
+    fi
   elif (( process_state == 2 )); then
     if [[ -n "${DEVICE_SERVICE_NAME:-}" ]]; then
       service_name="${DEVICE_SERVICE_NAME} [Unstable]"
@@ -135,10 +140,10 @@ device_detect_usb() {
   elif (( process_state == 130 )); then
     return 130
   fi
- 
+
   local sid=$(__get_usb_prop "$tty" "SERIAL_DEVICE_ID")
 
-  if (( process_state == 1 )) then
+  if (( process_state == 1 )); then
     echo "✓ Device not in use"
   elif [[ -n $sid ]]; then
     echo "⚠ Warning: Custom device in use by: ${service_name:-$process_name}"
@@ -148,18 +153,19 @@ device_detect_usb() {
   else
     echo "✗ Error: Device in use by: ${service_name:-$process_name}"
   fi
- 
+
+
   json_props["port"]="$tty"
   json_props["process"]="$process_name"
   json_props["service"]="$service_name"
   json_props["usbProps"]="$usb_props"
+	# shellcheck disable=SC2034  # passed byref
   json_props["sid"]="$sid"
- 
+
   echo "Done"
 
-  # keep last
-  __device_send_props_as_json json_props
-  
+  __device_send_props_to_json_result json_props
+
   return 0
 }
 
@@ -167,8 +173,8 @@ device_detect_usb() {
 # device_apply <tty> <service path> <usp props>
 # usage "ttyUSB0" "Inetbox" $usbProps
 device_apply() {
- 
-  local service_path="$1"
+
+  local device_path="$1"
   local tty="$2"
   local usbProps="$3"
   local usbProps_current=
@@ -176,30 +182,29 @@ device_apply() {
   echo "Installing USB serial device..."
 
   # check passed args
-  [[ -z "${service_path}" ]] && { echo "device_apply: Error: Service path not passed" >&2; return 1; }
+  [[ -z "${device_path}" ]] && { echo "device_apply: Error: Service path not passed" >&2; return 1; }
   [[ -z "${tty}" ]] && { echo "device_apply: Error: tty not passed" >&2; return 1; }
   [[ -z "${usbProps}" ]] && { echo "device_apply: Error: usbProps not passed" >&2; return 1; }
 
   # check tty is still valid, if so get props
-  [[ -e "/dev/${tty}" ]] && { __fill_usb_props "${tty}" "${service_path}" usbProps_current; }
-  
-  # compare props with passed props to detect if device is the same as the one detected 
+  [[ -e "/dev/${tty}" ]] && { __fill_usb_props "${tty}" "${device_path}" usbProps_current; }
+
+  # compare props with passed props to detect if device is the same as the one detected
   # in device_detect_usb.
   [[ "${usbProps_current}" != "${usbProps}" ]] && { echo "Usb device has changed. Re-detect" >&2; return; }
- 
-  local sid=$(__get_usb_prop $tty SERIAL_DEVICE_ID)
 
-  #if [[ -n $sid ]]; then
-  #  echo "Removing existing serial starter rule"
-  #  device_remove "$sid" "$tty" || \
-  #    echo "⚠ Warning: failed to remove existing serial starter rule"
-  #fi
+  local sid=;sid=$(__get_usb_prop "$tty" SERIAL_DEVICE_ID)
+
+  if [[ -n $sid ]]; then
+    echo "Removing existing serial starter rule"
+    device_remove "$sid"
+  fi
 
   # get dbus values
-  local dbus_path_prefix="/Settings/OpkgManager/CustomServices"
+  local dbus_path_prefix="/Settings/OpkgManager/CustomDevices"
   local service_name= usb_mapping_name=
-  dbus_common_get_value "${dbus_path_prefix}/${service_path}/ServiceName" service_name
- 
+  dbus_common_get_value "${dbus_path_prefix}/${device_path}/ServiceName" service_name
+
   # fill serial-starter-installer variables
   DEVICE_UDEV_PROPS="${usbProps}"
   DEVICE_TTY="${tty}"
@@ -212,22 +217,36 @@ device_apply() {
     echo "✗ Failed"
     return 1
   }
-  
+
+	local dbus_path="/Settings/CustomDevices/sid_$DEVICE_SID"
+	local vendorName=;vendorName=$(__get_usb_prop "$tty" ID_VENDOR)
+	local modelName=;modelName=$(__get_usb_prop "$tty" ID_MODEL)
+	local productName=
+
+	dbus_common_add_dbus_csv_values "/Settings/CustomDevicesList" "$DEVICE_SID"
+	dbus_common_get_value "${dbus_path_prefix}/${device_path}/ProductName" productName
+	dbus_common_add_settings <<< "
+			{'path':'$dbus_path/DeviceVendor', 'default': '$vendorName'},
+			{'path':'$dbus_path/DeviceModel', 'default': '$modelName'},
+			{'path':'$dbus_path/ProductName', 'default': '$productName'},
+	"
+
   # ensure serial starter service is running
   if [[ "$(svstat /service/serial-starter)" == *"serial-starter: down"* ]]; then
     echo "⚠ Warning: serial-starter: down. Restarting..."
     svc -u /service/serial-starter
   fi
 
-  # start our service
+  # start the service
   echo "Starting service..."
 
-  local r= out_pid=;
-  device_get_stable_tty_process_pid "$SERVICE_PATH/$DEVICE_SERVICE_NAME.$DEVICE_TTY" out_pid; r=$?
+  local r= _=;
+  device_get_stable_tty_process_pid "$device_path/$DEVICE_SERVICE_NAME.$DEVICE_TTY" _
+	r=$?
   ((r==130)) && return 130; # cancelled
   ((r==1)) && { echo "✗ Service not started"; return 1; }
   ((r==2)) && { echo "✗ Service not stable"; return 1; }
-  
+
   echo "~~✓ Starting service"
   echo "✓ Done"
   return 0
@@ -244,7 +263,7 @@ device_get_usb_port() {
   local -n _tty="$1"
   local UDEV_PID=""
   local FIFO_PATH=""
- 
+
 _device_cleanup_udevadm() {
   echo "_device_cleanup_udevadm"
   if [[ -n "$UDEV_PID" ]]; then
@@ -261,22 +280,22 @@ _device_cleanup_udevadm() {
   fifo=$(mktemp -u)
   mkfifo "$fifo"
   FIFO_PATH="$fifo"
-  
-  trap '_device_cleanup_udevadm' SIGTERM SIGINT 
+
+  trap '_device_cleanup_udevadm' SIGTERM SIGINT
 
   udevadm monitor --subsystem-match=tty -u > "$fifo" &
- 
+
   UDEV_PID=$!
   # ---
   # NOTE: Bash signal handling (traps) only occure between commands.
   # If we use a blocking read, Bash cannot process signals (like SIGTERM)
   # and the process will not exit until the read returns.
-  # By using a timed read (-t 1) on $fifo, we allow Bash to periodically 
-  # check for signals and run the trap handler, so the process can be 
+  # By using a timed read (-t 1) on $fifo, we allow Bash to periodically
+  # check for signals and run the trap handler, so the process can be
   # stopped/cancelled gracefully.
   # The loop only exits if the FIFO is removed or closed.
   # ---
-  
+
   while true; do
     if read -r -t 0.5 line < "$fifo"; then
       if [[ "$line" =~ ^UDEV\ .*[\[][0-9]*\.[0-9]*[]]\ add\  ]]; then
@@ -295,11 +314,11 @@ _device_cleanup_udevadm() {
         break
     fi
   done < "$fifo"
- 
+
   # Remove FIFO (cleanup will also do this, but for safety)
   rm -f "$fifo"
   FIFO_PATH=""
-  
+
 }
 
 # __get_usb_prop <tty> <property name>
@@ -314,7 +333,7 @@ __fill_usb_props() {
   local tty="$1"
   local service_path="$2"
   local -n udevadm_props_ref="$3"
-  local prop val found_name
+  local prop val
   local udevadm_out udevadm_props=""
   local usb_prop_names=
   local -a __props
@@ -323,11 +342,11 @@ __fill_usb_props() {
   udevadm_props_ref=""
 
   # Get props to retrieve using the service_path else use defaults
-  dbus_common_get_value "/Settings/OpkgManager/CustomServices/${service_path}/UsbProps" usb_prop_names
+  dbus_common_get_value "/Settings/OpkgManager/CustomDevices/${service_path}/UsbProps" usb_prop_names
   [[ -z $usb_prop_names ]] && usb_prop_names="$DEFAULT_USB_PROPS"
-  
+
   udevadm_out=$(udevadm info --query=property --name="$tty" 2>/dev/null)
-  
+
   IFS=',' read -r -a __props <<< "$usb_prop_names"
   for prop in "${__props[@]}"; do
     [[ ${prop:0,1} == "+" ]] && prop=${prop:1}
@@ -342,7 +361,7 @@ __fill_usb_props() {
   fi
 
 }
-  
+
 # device_get_stable_tty_process_pid <tty|service_path> <out_pid> [out_possible_names] [stable_checks]
 # Samples a tty or service path and returns success once the same PID has been
 # observed for the requested number of consecutive checks.
@@ -352,7 +371,7 @@ __fill_usb_props() {
 #   2 = unstable startup detected before becoming stable
 #   3 = invalid arguments
 device_get_stable_tty_process_pid() {
- 
+
   local service="" tty=""
   local -n __out_pid="${2}"
   local __out_possible_names_name="${3:-}"
@@ -373,7 +392,7 @@ device_get_stable_tty_process_pid() {
   (( max_checks = stable_checks * 4 ))
 
   trap 'cancelled=1' SIGINT SIGTERM
- 
+
   __out_pid=
   [[ -n "$__out_possible_names_name" ]] && printf -v "$__out_possible_names_name" '%s' ""
 
@@ -435,35 +454,36 @@ device_get_stable_tty_process_pid() {
   trap - SIGINT SIGTERM
   (( cancelled )) && return 130
   (( success )) && return 0
-  
+
   while IFS= read -r possible_name; do
     [[ -z "$possible_name" ]] && continue
     [[ -n "$joined_possible_names" ]] && joined_possible_names+=" or "
     joined_possible_names+="$possible_name"
   done < <(printf '%s\n' "${!possible_names[@]}" | sort)
   [[ -n "$__out_possible_names_name" ]] && printf -v "$__out_possible_names_name" '%s' "$joined_possible_names"
- 
+
   (( observed_any == 1 || unstable_seen == 1 )) && return 2
   return 1
 }
- 
+
 device_find_service_from_pid() {
   local pid="$1" ppid comm
   local tty="$2"
   local -n out_service_name="$3"
   out_service_name=""
   local __service_name=
- 
+
   while [[ -n "$pid" && "$pid" -gt 1 ]]; do
-    
+
     comm="$(ps -p "$pid" -o comm= 2>/dev/null | tr -d ' ')"
 
     if [[ "$comm" == "supervise" ]]; then
      __service_name="$(basename "$(readlink -f "/proc/$pid/cwd")")"
      if [[ -d "/service/${__service_name}.${tty}" ]] ; then
         out_service_name="${__service_name}.${tty}"
-        return 0  
+        return 0
       elif [[ -d "/service/${__service_name}" ]] ; then
+				# shellcheck disable=SC2034 # byref
         out_service_name="${__service_name}"
         return 0
       fi
@@ -475,7 +495,7 @@ device_find_service_from_pid() {
   done
   return 1
 }
- 
+
 device_remove_all() {
   for arg in "$@"; do
     device_remove "$arg"
@@ -484,17 +504,13 @@ device_remove_all() {
 
 device_remove() {
 
-  local dbus_service_name="${1}" # dbus_inetbox_sid_5f90
-  [[ -z "$dbus_service_name" ]] && return 1
+  DEVICE_SID="${1}"
+  [[ -z "$DEVICE_SID" ]] && { echo "Invalid argument: sid empty" >&2; return 1; }
 
-  DEVICE_SERVICE_NAME=
-  DEVICE_SID=
-  DEVICE_TTY="${2:-}"
+	# echo "/Settings/CustomDevices/sid_${DEVICE_SID}" >&2
 
-  dbus_common_get_value "/Settings/Devices/${dbus_service_name}/Sid" DEVICE_SID
-  dbus_common_delete_tree "Devices/${dbus_service_name}"
-
-  [[ -z "$DEVICE_SID" ]] && return 1
+  dbus_common_delete_tree "/Settings/CustomDevices/sid_${DEVICE_SID}"
+	dbus_common_remove_dbus_csv_values "/Settings/CustomDevicesList" "$DEVICE_SID"
 
   serial_device_installer_remove_service
 
@@ -509,7 +525,7 @@ case "${1:-}" in
 		;;
   apply)
     shift
-    device_apply "${1:-}" "${2:-}" "${3:-}" 
+    device_apply "${1:-}" "${2:-}" "${3:-}"
     ;;
   remove)
     shift
diff --git a/addons/opkg-manager/src/data/opkg-manager/opkg-common b/addons/opkg-manager/src/data/opkg-manager/opkg-common
--- a/addons/opkg-manager/src/data/opkg-manager/opkg-common
+++ b/addons/opkg-manager/src/data/opkg-manager/opkg-common
@@ -21,7 +21,7 @@ declare __this_path; __this_path="$(dirname "${BASH_SOURCE[0]}")"
 
 # Expand rootfs and make it writable
 opkg_common_expand_root_fs() {
-  
+
   log_trace "expanding root fs"
   if [[ ! $dry_run ]]; then
     $resize2fs_file
@@ -50,7 +50,7 @@ __mount_root_fs_readonly() {
 # if initial state is empty but ___is_fs_readonly now
 # has a value then we restore back to readonly.
 __restore_previous_fs_access() {
-  
+
   log_trace "Restoring previous fs state"
 
   if [[ "${___is_fs_readonly}" = 1 ]]; then
@@ -59,18 +59,18 @@ __restore_previous_fs_access() {
     log_trace "previous state was readwrite; nothing to restore"
   fi
   ___is_fs_readonly=
-  
+
 }
 
 opkg_common_ensure_feed_symlink() {
 
   local new_target="/data/conf/opkg-manager-feeds-${1:-release}.conf"
 
-  [[ ! -f "${new_target}" ]] && { 
+  [[ ! -f "${new_target}" ]] && {
     log_error "feed target file does not exist: ${new_target}"; }
 
   local current_source=""
-  [[ -L "${OPKG_FEED_CONFIG_FILE_SYMLNK}" ]] && 
+  [[ -L "${OPKG_FEED_CONFIG_FILE_SYMLNK}" ]] &&
     current_source="$(readlink "${OPKG_FEED_CONFIG_FILE_SYMLNK}")"
 
   if [[ "${current_source}" == "${new_target}" ]]; then
@@ -103,14 +103,15 @@ opkg_common_feed_add() {
 
   if grep -qE "^src/gz ${feed_name} " "${OPKG_FEED_CONFIG_FILE_SYMLNK}" ||
     grep -qE "^src/gz ${feed_name} " "/etc/opkg/venus.conf"; then
-    log_trace "Feed already exists: ${feed_name}"
-    return 0
+    log_error "Feed already exists: ${feed_name}" >&2; return 1;
   fi
 
-  echo "src/gz ${feed_name} ${feed_url}" >> "${OPKG_FEED_CONFIG_FILE_SYMLNK}" || {
-    log_error "Error writing feed: ${feed_name}"
-    return 1
-  }
+	# make sure we update the real file and not the symlink
+	local feedfile="${OPKG_FEED_CONFIG_FILE_SYMLNK}"
+  [[ -L "${feedfile}" ]] && feedfile="$(readlink "${OPKG_FEED_CONFIG_FILE_SYMLNK}")"
+
+	echo "src/gz ${feed_name} ${feed_url}" >> "${feedfile}" \
+			|| { echo "Error writing to ${feedfile}" >&2; return 1; }
 
   return 0
 }
@@ -210,7 +211,7 @@ feed_get_feed_type() {
     feedType="${feedType%.conf}"  # remove suffix
   fi
   # default to release, as opkg_common_ensure_feed_symlink will take care of missing conf.
-  echo "${feedType:-release}" 
+  echo "${feedType:-release}"
 }
 
 opkg_common_remove_feed_symlink() {
@@ -241,9 +242,9 @@ __wait_for_opkg() {
 
 opkg_common_update_packages() {
   (
-    __wait_for_opkg && opkg update 
+    __wait_for_opkg && opkg update
   ) &
-  
+
   local opkg_pid=$!
   wait "$opkg_pid"
   return 0
@@ -254,7 +255,7 @@ __ensure_rc_local() {
   if [[ ! -f "${rc_local_file}" ]]; then
     log "rc.local does not exist; creating..."
     if [[ ! $dry_run ]]; then
-      touch "${rc_local_file}"  
+      touch "${rc_local_file}"
     fi
   fi
   if [[ ! $dry_run ]]; then
@@ -281,7 +282,7 @@ __init_root_fs_for_writing() {
     else
       ___is_fs_readonly=0
     fi
- 
+
     if [[ "${___is_fs_readonly}" = 1 ]]; then
       __root_fs_readwrite
     fi
@@ -307,13 +308,13 @@ __init_opkg() {
 
   log_trace "__init_opkg: initializing"
 
-  opkg_common_ensure_feed_symlink 
+  opkg_common_ensure_feed_symlink
   if [[ ! $dry_run ]]; then
     opkg update
   fi
 
   init_opkg_helpers=1
- 
+
 }
 
 __opkg_common_try_install_package() {
@@ -347,7 +348,7 @@ __opkg_common_try_install_package() {
 }
 
 # loops through all the lines in
-# the opkg_installed_packages_file 
+# the opkg_installed_packages_file
 # and proceeds to install each
 # package.
 # takes care of read write access
@@ -357,7 +358,7 @@ opkg_common_ensure_installed() {
      log "opkg_installed_packages_file does not exist"; return 0; }
 
   log_trace "opkg_common_ensure_installed"
- 
+
   log_push_indent
   local isfirst=1
 
@@ -365,15 +366,15 @@ opkg_common_ensure_installed() {
   do
     # ignore comments and empty lines
     [[ -z "${line//[[:space:]]/}" || $line == \#* ]] && continue
-    
+
     if ((isfirst)); then
       isfirst=0
     else
       sleep 1
     fi
- 
+
     __wait_for_opkg
-    
+
     __opkg_common_try_install_package "${line}"
 
   done < "${opkg_installed_packages_file}"
@@ -386,7 +387,7 @@ opkg_common_ensure_installed() {
 
   return 0
 }
- 
+
 # adds script to the rc_local file
 # args: ${1} the script to add
 # this script can be multiple lines
@@ -427,16 +428,16 @@ opkg_common_remove_script_from_rc_local() {
   # string_lib_multiline_find_replace "${1}" --trim-lines < "${rc_local_file}" > "${rc_local_file}"
 
   if [[ ! $dry_run ]]; then
-  
+
   thispath="$(dirname "${BASH_SOURCE[0]}")"
   . "$thispath/libs/string-lib"
-    
+
     # TODO add inplace option to string_lib_multiline_find_replace
     local tmp; tmp=$(mktemp)
     string_lib_multiline_find_replace "${1}" --trim-lines < "${rc_local_file}" > "$tmp" && {
       mv "$tmp" "${rc_local_file}"
     }
-     
+
   fi
 
 }
@@ -450,7 +451,7 @@ opkg_common_register_package() {
   [[ -z "${1:-}" ]] && { log_error "ERROR: no package name supplied" ; return 1; }
 
   local package_name="${1:-}"
-  
+
   if [[ ! -f "${opkg_installed_packages_file}" ]] || ! grep -q "^${package_name}$" "${opkg_installed_packages_file}" ; then
     log "Adding ${package_name} to ${opkg_installed_packages_file}"
     if [[ ! $dry_run ]]; then
@@ -490,7 +491,7 @@ case "${1:-}" in
     fi
     opkg_common_ensure_installed
     ;;
- 
+
   ensure-feeds)
     shift
     opkg_common_ensure_feed_symlink "${1:-}"
